on: [push, pull_request]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        job_name: ['macos']

        include:
        - job_name: macos
          os: macos-latest
          shell: bash {0}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: hactool-${{ matrix.job_name }}
    runs-on: ${{ matrix.os }}

    - uses: actions/checkout@v4.2.2

    - run: |
        mv config.mk.template config.mk
        make -j$(nproc)

    - uses: actions/upload-artifact@v4.6.2
      with:
        name: hactool-${{ matrix.job_name }}
        path: hactool*
