on: [push, pull_request]

jobs:
  build:
    name: hactool-macos
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Build hactool
        shell: bash
        run: |
          mv config.mk.template config.mk
          make -j$(sysctl -n hw.ncpu)

      - name: Upload hactool binary
        uses: actions/upload-artifact@v4.6.2
        with:
          name: hactool-macos
          path: hactool*
